import {useEffect,useState} from "react";
import {BarChart3,CheckCircle2,RefreshCw,ShieldAlert,TrendingUp} from "lucide-react";
const API="http://127.0.0.1:8788";
async function post(path:string,body:any){const r=await fetch(API+path,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});if(!r.ok)throw Error(await r.text());return r.json()}
export default function AgentIntelligence(){
 const [analytics,setAnalytics]=useState<any[]>([]),[recommendations,setRecommendations]=useState<any[]>([]),[outcomes,setOutcomes]=useState<any[]>([]),[error,setError]=useState("");
 const load=async()=>{try{const scope={tenant_id:"default",workspace_id:"command-center"};const [a,r,o]=await Promise.all([post("/sales/agent/outcomes/analytics",scope),post("/sales/agent/outcomes/recommendations",scope),post("/sales/agent/outcomes",{...scope,limit:12})]);setAnalytics(a);setRecommendations(r);setOutcomes(o);setError("")}catch(e){setError("Agent intelligence unavailable.")}};
 useEffect(()=>{load()},[]);
 const total=analytics.reduce((n,x)=>n+x.total,0),completed=analytics.reduce((n,x)=>n+x.completed,0),failed=analytics.reduce((n,x)=>n+x.failed,0),rate=total?Math.round(completed/Math.max(1,total-analytics.reduce((n,x)=>n+x.blocked,0))*100):0;
 return <><div className="metrics"><div className="metric"><BarChart3 size={18}/><div><strong>{total}</strong><span>Recorded outcomes</span></div></div><div className="metric"><CheckCircle2 size={18}/><div><strong>{rate}%</strong><span>Effective success</span></div></div><div className="metric"><ShieldAlert size={18}/><div><strong>{failed}</strong><span>Failed actions</span></div></div><div className="metric"><TrendingUp size={18}/><div><strong>{analytics.filter(x=>x.signal==="stable_success").length}</strong><span>Stable actions</span></div></div></div>
 <div className="grid two"><section className="card"><div className="card-title"><div><BarChart3 size={17}/><b>Evidence by Action</b></div><button className="icon-btn" onClick={load}><RefreshCw size={15}/></button></div><div className="intelligence-list">{analytics.length?analytics.map((x:any)=><div className="intel-row" key={x.action}><div><b>{x.action}</b><small>{x.total} samples · {Math.round(x.success_rate*100)}% success</small></div><span className={x.signal==="repeat_failure"?"signal danger":x.signal==="stable_success"?"signal success":"signal"}>{x.signal.replaceAll("_"," ")}</span></div>):<p>No execution evidence yet.</p>}</div></section>
 <section className="card"><div className="card-title"><div><ShieldAlert size={17}/><b>Strategy Guidance</b></div><span className="pill">Governed</span></div>{recommendations.length?recommendations.map((x:any)=><div className="intel-row" key={x.action}><div><b>{x.action}</b><small>{x.reason||x.signal}</small></div><span className="signal">{x.recommendation}</span></div>):<p>No recommendations yet.</p>}</section></div>
 <section className="card"><div className="card-title"><div><TrendingUp size={17}/><b>Recent Outcome Ledger</b></div><span className="pill">Tenant scoped</span></div><div className="intel-table">{outcomes.map((x:any)=><div className="intel-row" key={x.outcome_id}><div><b>{x.action}</b><small>{x.plan_id} · {x.reason_code}</small></div><span className={x.outcome==="completed"?"signal success":x.outcome==="failed"?"signal danger":"signal"}>{x.outcome}</span></div>)}</div></section>{error&&<div className="alert">{error}</div>}</>;
}
