import {useEffect,useState} from "react";
import {AlertTriangle,CheckCircle2,FileText,RefreshCw,ShieldCheck,TriangleAlert} from "lucide-react";
const API="http://127.0.0.1:8788";
async function post(path:string,body:any){const r=await fetch(API+path,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});if(!r.ok)throw Error(await r.text());return r.json()}
function Pill({children,kind="neutral"}:{children:any,kind?:string}){return <span className={"pill "+kind}>{children}</span>}
function Metric({label,value,icon:Icon}:{label:string,value:any,icon:any}){return <div className="metric"><Icon size={18}/><div><strong>{value}</strong><span>{label}</span></div></div>}
export default function Compliance(){
 const [summary,setSummary]=useState<any>(null),[gaps,setGaps]=useState<any[]>([]),[recs,setRecs]=useState<any[]>([]),[report,setReport]=useState<any>(null),[msg,setMsg]=useState("");
 const load=async()=>{try{const body={tenant_id:"default",workspace_id:"command-center"};const [s,g,r]=await Promise.all([post("/compliance/summary",body),post("/compliance/gaps",body),post("/compliance/recommendations",body)]);setSummary(s);setGaps(g.gaps||[]);setRecs(r.recommendations||[]);setMsg("")}catch(e){setMsg("Compliance API unavailable.")}};
 useEffect(()=>{load()},[]);
 const generate=async()=>{try{setReport(await post("/compliance/report/generate",{tenant_id:"default",workspace_id:"command-center",generated_by:"command-center"}))}catch(e){setMsg("Report generation failed.")}};
 return <><div className="page-head"><div><div className="eyebrow">COMPLIANCE CONTROL PLANE</div><h2>Compliance Command Center</h2><p>Evidence-driven obligations, controls, risks, gaps and reviewable reports.</p></div><button className="secondary" onClick={load}><RefreshCw size={16}/>Refresh</button></div>
 <div className="metrics"><Metric label="Obligations" value={summary?.obligations??"-"} icon={FileText}/><Metric label="Verified evidence" value={summary?.verified_evidence??"-"} icon={CheckCircle2}/><Metric label="High/Critical risks" value={summary?.open_high_or_critical_risks??"-"} icon={TriangleAlert}/><Metric label="Open gaps" value={summary?.gaps??"-"} icon={AlertTriangle}/></div>
 <div className="grid two"><section className="card"><div className="card-title"><div><AlertTriangle size={17}/><b>Detected Gaps</b></div><Pill>{gaps.length}</Pill></div>{gaps.length===0?<p>No gaps detected in the current scoped matrix.</p>:<div className="intelligence-list">{gaps.slice(0,12).map((g:any,i:number)=><div className="intel-row" key={i}><div><strong>{g.title}</strong><span>{g.type} · {g.reference_id}</span></div><Pill kind={g.priority==="critical"||g.priority==="high"?"danger":"warning"}>{g.priority}</Pill></div>)}</div>}</section>
 <section className="card"><div className="card-title"><div><ShieldCheck size={17}/><b>Recommendations</b></div><Pill>{recs.length}</Pill></div>{recs.length===0?<p>No recommendations currently generated.</p>:<div className="intelligence-list">{recs.slice(0,12).map((r:any,i:number)=><div className="intel-row" key={i}><div><strong>{r.recommendation}</strong><span>{r.gap_type} · {r.reference_id}</span></div><Pill>{r.priority}</Pill></div>)}</div>}</section></div>
 <section className="card"><div className="card-title"><div><FileText size={17}/><b>Evidence-backed Report</b></div><Pill>Human review</Pill></div><p>Generate a persisted draft from the current compliance matrix. Approval remains a separate human decision.</p><button className="primary" onClick={generate}>Generate report</button>{report&&<div className="id-grid"><span>Report<strong>{report.report_id||report.report?.report_id||"created"}</strong></span><span>Status<strong>{report.status||report.report?.status||"draft"}</strong></span></div>}</section>{msg&&<div className="alert"><AlertTriangle size={17}/>{msg}</div>}</>;
}
