import {useEffect,useState} from "react";
import {BookOpen,BrainCircuit,CheckCircle2,Database,LockKeyhole,Search} from "lucide-react";
import {Metric,StaticPanel,Pill,get,post} from "./ui_parts";
export default function Knowledge(){
 const [health,setHealth]=useState<any>(null),[q,setQ]=useState(""),[results,setResults]=useState<any[]>([]),[content,setContent]=useState(""),[source,setSource]=useState("command-center"),[msg,setMsg]=useState("");
 const load=async()=>{try{setHealth(await get("/knowledge/health"))}catch(e){setMsg("Knowledge API unavailable.")}}; useEffect(()=>{load()},[]);
 const search=async()=>{try{const r=await post("/knowledge/search",{query:q,tenant_id:"default",workspace_id:"command-center"});setResults(r.results||[])}catch(e){setMsg("Search failed.")}};
 const ingest=async()=>{try{if(!content.trim())return;await post("/knowledge/ingest",{content,source,source_type:"ui",tenant_id:"default",workspace_id:"command-center",actor_id:"founder",role:"admin",trust:"verified",knowledge_trust:"verified"});setContent("");setMsg("Knowledge ingested and persisted.");load()}catch(e){setMsg("Ingestion failed.")}};
 return <><div className="metrics"><Metric label="Stored knowledge" value={health?.knowledge_count??0} icon={Database}/><Metric label="Storage" value={health?.storage??"SQLite"} icon={CheckCircle2}/><Metric label="Retrieval" value={health?.retrieval_mode??"keyword"} icon={BrainCircuit}/><Metric label="Scope" value="Tenant + Workspace" icon={LockKeyhole}/></div><div className="grid two"><StaticPanel title="Memory + RAG Intelligence Engine" icon={BrainCircuit}><div className="feature-list"><b>Semantic retrieval</b><span>Embedding layer planned; current runtime uses keyword retrieval.</span><b>Keyword retrieval</b><span>Exact-term matching is live.</span><b>Relevance scoring</b><span>Token overlap with trust and scope filters.</span></div></StaticPanel><section className="card"><div className="card-title"><div><Database size={17}/><b>Ingest Knowledge</b></div><Pill kind="success">LIVE</Pill></div><input value={source} onChange={e=>setSource(e.target.value)} placeholder="Source"/><textarea value={content} onChange={e=>setContent(e.target.value)} placeholder="Approved knowledge content…"/><button className="primary" onClick={ingest}><BookOpen size={16}/> Ingest</button></section></div><section className="card"><div className="card-title"><div><Search size={17}/><b>Knowledge Search</b></div><Pill>{results.length} results</Pill></div><div className="command-actions"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search approved knowledge…"/><button className="primary" onClick={search}><Search size={16}/> Search</button></div>{msg&&<p>{msg}</p>}<div className="cap-list">{results.map((r:any)=><div key={r.knowledge_id}><CheckCircle2 size={15}/><b>{r.source}</b> · {r.trust} · score {r.score}<span>{r.content?.slice(0,180)}</span></div>)}</div></section></>}
